# Generated by Django 5.2.6 on 2025-09-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('mod_num', models.IntegerField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=20)),
                ('car_color', models.CharField(max_length=20)),
                ('car_num', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
